# Generated by Django 5.1 on 2024-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_remove_recommendation_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
