# Generated by Django 5.1 on 2024-08-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_like_user_alter_recommendation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
