# Generated by Django 5.1 on 2024-08-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='book.book'),
        ),
    ]
